theme: jekyll-theme-minimal
title: Geri's homepage
description: Bookmark this to keep an eye on my project updates!

url: https://faintskygames.github.io # the base hostname & protocol for your site
last_updated: true # set to true if you want to display last updated in the footer